name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      
      - name: Setup Deno 1.x
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
            
      - name: Setup Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Check fmt
        run: deno fmt --check
      
      - name: Install dependencies
        run: pnpm i

      - name: Test
        run: pnpm test
